name: Finalize Release

on:
  workflow_run:
    workflows:
      - "Build & Release Linux (AMD64/AppImage)"
      - "Build & Release Linux (AMD64/Zip)"
      - "Build & Release Linux (ARM64/AppImage)"
      - "Build & Release Linux (ARM64/Zip)"
      - "Build & Release MacOs (AMD64/dmg)"
      - "Build & Release MacOs (ARM64/dmg)"
      - "Build & Release Windows (AMD64/Zip)"
    types:
      - completed

jobs:
  finalize-release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Download artifacts from each workflow
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: ./all-artifacts/windows

      - name: Download Linux AMD64 AppImage
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64-appimage
          path: ./all-artifacts/linux-amd64-appimage

      - name: Download Linux AMD64 Zip
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64-zip
          path: ./all-artifacts/linux-amd64-zip

      - name: Download Linux ARM64 AppImage
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-appimage
          path: ./all-artifacts/linux-arm64-appimage

      - name: Download Linux ARM64 Zip
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-zip
          path: ./all-artifacts/linux-arm64-zip

      - name: Download MacOS AMD64 dmg
        uses: actions/download-artifact@v4
        with:
          name: macos-amd64-dmg
          path: ./all-artifacts/macos-amd64-dmg

      - name: Download MacOS ARM64 dmg
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-dmg
          path: ./all-artifacts/macos-arm64-dmg

      # 3️⃣ Upload all artifacts to draft release
      - name: Upload all artifacts to draft release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          draft: true
          files: ./all-artifacts/**/*   # recursively include all files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Publish final release
      - name: Publish final release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
