name: Finalize Release

on:
  workflow_run:
    workflows:
      - "Build & Release Linux (AMD64/AppImage)"
      - "Build & Release Linux (AMD64/Zip)"
      - "Build & Release Linux (ARM64/AppImage)"
      - "Build & Release Linux (ARM64/Zip)"
      - "Build & Release MacOs (AMD64/dmg)"
      - "Build & Release MacOs (ARM64/dmg)"
      - "Build & Release Windows (AMD64/Zip)"
    types:
      - completed

jobs:
  finalize-release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Download all artifacts from previous workflows
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: all-artifacts
          path: ./all-artifacts

      # 3️⃣ Upload all artifacts to the draft release
      - name: Upload all artifacts to draft release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          draft: true
          files: ./all-artifacts/**/*   # recursively include all files from centralized folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Publish the draft release as final release
      - name: Publish final release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
